version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: nexus-ide-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nexus-network

  # Redis (We will need this later for scaling the collab server)
  redis:
    image: redis:alpine
    container_name: nexus-ide-redis
    ports:
      - "6379:6379"
    networks:
      - nexus-network

volumes:
  mongodb_data:

networks:
  nexus-network:
    driver: bridge